[package]
name = "hemogoblin"
version = "0.0.2"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
description = "Safe, high-level bindings to libPlasma"
readme = "README.md"

[dependencies]
plasma-sys = { path = "../plasma-sys", version = "0.0.2" }
