[package]
name = "plasma-sys"
version = "0.0.2"
edition = "2024"
license = "MIT"
publish = true
description = "FFI bindings for libPlasma"
readme = "README.md"

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.41"
